services:
  firewall:
    build: ./firewall
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"

  client:
    build: ./client
    network_mode: "service:firewall"
    tty: true
    stdin_open: true


  control:
    build: ./control
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - firewall
    command: ["bash", "-lc", "sleep infinity"]
    tty: true
    stdin_open: true
